import type { Metadata } from 'next'
import '@styles/global.css'

//components
import {Sidebar, SidebarItem} from "@components/sidebar" 

//icon
import {
  Package, 
  Truck, 
  Bell, 
  Wallet, 
  MessageCircle
} from "lucide-react"

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body>
        <Sidebar>
            <SidebarItem icon={<Package />} text="Envoies" active={true} alert={false}/>
            <SidebarItem icon={<Truck />} text="Transports" active={false} alert={false}/>
            <hr className="my-3"/>
            <SidebarItem icon={<Wallet />} text="Portefeuille" active={false} alert={false}/>
            <SidebarItem icon={<Bell />} text="Notifications" active={false} alert={true}/>
            <SidebarItem icon={<MessageCircle />} text="Messages" active={false} alert={true}/>
        </Sidebar>
        <main className="w-full pl-24 h-screen bg-black">{children}</main>
      </body>
    </html>
  )
}
